### ISSUE TITLE
`export_test.go` pattern yields "Unresolved Reference" messages

### ISSUE THREAD

**Issue by anpep** [tooltitude/support#24] opened 2023-10-23 11:14 UTC
Tooltitude Version: v0.41.0

OS Version: `Linux ubuntu 6.4.16-orbstack-00105-g14094bfeec09 #1 SMP Mon Sep 18 21:45:38 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`

VS Code Version: 1.83.1

Go Version: `go version go1.20.10 linux/arm64`

Code Repository (if open source):

What did you try to do?

I exported some symbols on a file named `export_test.go` under the package name `grubenv_test`. However, these symbols are not correctly resolved on other files under the `grubenv_test` package.

<img width="602" alt="Screenshot 2023-10-23 at 13 09 15" src="https://github.com/tooltitude/support/assets/55109673/72a90fab-6e93-4232-b9ae-51982c96c7d8">

**Comment by tooltitude-support** [comment] 2023-10-23 12:56
@anpep Thank you for the feedback and helping us reproduce the issue.

It looks like we have a package abc, we could import it not only without a package prefix but also via abc. prefix. I was able to reproduce it. Fix will be soon (my best guess is today), most likely in 0.41.1 patch fix, which we will likely release today or tomorrow.

**Comment by tooltitude-support** [comment] 2023-10-23 17:30
@anpep Ok. Fixed it. Will release 0.41.1 after a bit of testing, and cleanups.

**Comment by anpep** [comment] 2023-10-23 17:32
Thank you! Will stay tuned

**Comment by tooltitude-support** [comment] 2023-10-23 18:07
Ok. The build is out. Please update to 0.41.1 and check whether the problem disappear.

**Comment by tooltitude-support** [comment] 2023-10-23 22:09
UPD: The latest release is 0.41.2. One more issue is fixed.

**Comment by anpep** [comment] 2023-10-24 09:08
The problem did disappear. Thank you!

**Comment by anpep** [comment] 2023-10-25 12:26
The problem just reappeared, I don't understand why since I tried yesterday and it worked. Problem exists on both 0.41.2 and 0.41.3 :(

**Comment by tooltitude-support** [comment] 2023-10-25 12:35
@anpep Ooops. Do you have the same configuration as described? Or is there anything different?

**Comment by tooltitude-support** [comment] 2023-10-25 12:37
I used the following as the test case. Is yours any different?

<img width="478" alt="Screenshot 2023-10-25 at 8 36 48 AM" src="https://github.com/tooltitude/support/assets/123904466/c4e9768f-1ae1-44e5-b846-000b39dd5229">

**Comment by tooltitude-support** [comment] 2023-10-25 12:42
@anpep I see a GPL header. Is this code available anywhere on github?

**Comment by tooltitude-support** [comment] 2023-10-25 12:45
@anpep BTW, are you sure that it's a tooltitude bug, i.e. is there a tooltitude label in the popup which is shown when you hover over error?

**Comment by tooltitude-support** [comment] 2024-08-10 16:49
Closing it, since there were no updates for a pretty long time. Please create a new issue if you have it again.

**Closed by tooltitude-support** 2024-08-10 16:49 UTC
