### ISSUE TITLE
Weird "Unresolved Reference" error message

### ISSUE THREAD

**Issue by faceair** [tooltitude/support#8] opened 2023-04-12 16:04 UTC
Tooltitude Version:  v0.13.3

OS Version:  macOS 13.3.1

VS Code Version:  1.77.2

Go Version: 1.20.3

Code Repository (if open source): no

What did you try to do?

<img width="697" alt="image" src="https://user-images.githubusercontent.com/3659110/231515087-57d238b4-9af1-47aa-9d67-f0d72e99fda5.png">

<img width="527" alt="image" src="https://user-images.githubusercontent.com/3659110/231515174-954c5466-8a25-4b65-8dca-0215bf116356.png">

Is there anything interesting in the tooltitude output channel? (should be open if you are reporting error from within VS Code) no

My code is error-free, it compiles and runs without any issues. However, Tooltitude is giving me a strange error message and I have no idea what's causing it. There doesn't seem to be an option to disable it either.

I would like to:
1. have an option to disable all linting.
2. have the error message fixed.

**Comment by tooltitude-support** [comment] 2023-04-12 16:52
@faceair Thanks for your feedback. We will disable this lint by default in the next version. 

To help fix it, do you use any build tags?

**Comment by faceair** [comment] 2023-04-12 16:58
I am using arenas, so there is an environment variable GOEXPERIMENT=arenas, without any other tags.

**Comment by tooltitude-support** [comment] 2023-04-12 17:00
@faceair Ok. Then, it's not obvious what it might be. I have seen some problems like this with build tags (though, I don't have a good solution to support multiple tags at the same time and resolve all references, and be performant).

**Comment by faceair** [comment] 2023-04-12 17:06
The variable c is an interface that may have two implementations, but the methods of this DataType will always return a value of the DataType type. Not sure if this information is helpful to you.

**Comment by tooltitude-support** [comment] 2023-04-12 17:07
@faceair It's very helpful! I thought c is a package import.

**Comment by tooltitude-support** [comment] 2023-04-12 17:25
Added 2 new settings: tooltitude.brokenRefsEnabled, and tooltitude.deprRefsEnabled, the first one will disable the error you have. The fix will be available closer to the end of this week in 0.14.0, most likely on Friday.

**Comment by tooltitude-support** [comment] 2023-04-12 17:35
I tried reproducing it. I created a project with 2 package. abc and c

`package c

import "github.com/tooltitude/sandbox/abc"

func DoStuff2(c abc.Xyz) {
	c.DataType()
}

func DoStuff() {
	println("I did Stuff!")
}
`

`package abc

type DataType uint8

type Xyz interface {
	DataType() DataType
}
`

In DoStuff, DataType resolves well. Is your example similar to it, or is there any substantial difference? Do you use generics anywhere?

**Comment by faceair** [comment] 2023-04-12 17:40
I double-checked and your lint is also correct. This "c" only has two possible implementations, so the default branch is actually unreachable. This code will not produce any errors during compilation, but it seems that your lint is stricter.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/3659110/231539286-b6bd0b73-d10c-4a66-b847-230a8a768253.png">

**Comment by tooltitude-support** [comment] 2023-04-12 17:42
@faceair No, it doesn't take the control flow into account. Now, I see what's going on. It has default branch, and it doesn't assign any type to c, as far as I understand. I believe, I will be able to fix the issue now.

**Comment by tooltitude-support** [comment] 2023-04-12 17:46
Was able to completely reproduce your example:
<img width="537" alt="Screenshot 2023-04-12 at 1 45 49 PM" src="https://user-images.githubusercontent.com/123904466/231541020-0ca30e06-2df5-427e-8c00-cc0eb45e7dc5.png">

**Comment by tooltitude-support** [comment] 2023-04-12 17:46
@faceair Thanks a lot for all helpful details!

**Comment by tooltitude-support** [comment] 2023-04-12 18:07
@faceair Ok. Fixed it as well. Fix will be available in 0.14.0 as described previously. Will close this issue after that release.

**Comment by tooltitude-support** [comment] 2023-04-12 18:20
Also, since we have the reason for this issue fixed, I will keep this inspection on by default.

**Comment by faceair** [comment] 2023-04-12 18:23
I have another question. Actually, gopls supports shadown checking, but it is disabled by default. Does Tooltitude no longer need to provide this feature?

In fact, gopls has some very useful checkers that are also disabled by default. I have enabled these, for reference only.
```
"gopls": {
    "ui.diagnostic.analyses": {
      "nilness": true,
      "unusedvariable": true,
      "unusedwrite": true,
      "useany": true
    },
    "ui.diagnostic.staticcheck": true,
    "ui.semanticTokens": true
  }
```

**Comment by tooltitude-support** [comment] 2023-04-12 18:27
@faceair They are a bit different. The last time I checked, gopls, didn't check for package name conflicts while tooltitude does it.

**Comment by tooltitude-support** [comment] 2023-04-12 18:44
@faceair I tried it right now, and found one more difference (in addition to package shadows not displayed): gopls one doesn't work on code with errors, i.e. the example from the documentation doesn't show shadows if the variables aren't resolved. 

P.S. Concerning our approach to inspections, we aim to have a set inspections which are applicable to almost anyone writing go code as opposed to the ability to choose the one which you want to enable.

**Comment by solomatov** [comment] 2023-04-12 18:46
One more difference is that we don't report variables with name err, ok, and _ since they are shadowed so often that it's basically useless to warn about them.

**Comment by tooltitude-support** [comment] 2023-04-14 13:01
@faceair v0.14.0 is out. Closing this issue. Please reopen it if you have it again.

**Closed by tooltitude-support** 2023-04-14 13:01 UTC
