### ISSUE TITLE
Incorrect detect `Unused Import` error

### ISSUE THREAD

**Issue by d-enk** [tooltitude/support#36] opened 2024-03-21 15:12 UTC
Tooltitude Version: `v0.66.3`

OS Version: `Ubuntu 6.5.0-25.25~22.04.1-generic 6.5.13`

VS Code Version: `1.87.2`

Go Version: `1.22.1`

```go

package test

import (
	"context" // Unused Import

	. "github.com/smartystreets/goconvey/convey"
)

func init() {
	_ = So
	_ = context.Background
}

```

```go.mod
//go.mod
module test

go 1.22.1

require github.com/smartystreets/goconvey v1.8.1

require (
	github.com/gopherjs/gopherjs v1.17.2 // indirect
	github.com/jtolds/gls v4.20.0+incompatible // indirect
	github.com/smarty/assertions v1.15.0 // indirect
)

```

**Comment by tooltitude-support** [comment] 2024-03-21 15:14
Thanks for your feedback. It seems that it's an obvious bug. It shouldn't take a lot of time to fix, so I guess, it will be out in 0.67.0 which will likely be out tomorrow (or may be even today later).

**Comment by tooltitude-support** [comment] 2024-03-21 15:19
@d-enk I looked into it. It looks like "github.com/smartystreets/goconvey/convey" has a type named context, which might lead to context be wrongly resolved to. Could you enable broken references, and see whether Background is considered broken?

**Comment by tooltitude-support** [comment] 2024-03-21 15:21
Reproduced it on a toy example (no need to check it):

<img width="538" alt="Screenshot 2024-03-21 at 11 21 25 AM" src="https://github.com/tooltitude/support/assets/123904466/65438f18-785c-48f9-96a7-42e3eebf086c">

**Comment by tooltitude-support** [comment] 2024-03-21 15:54
Ok. Fixed the problem.
It will be out in 0.67.0 as I said.

**Comment by tooltitude-support** [comment] 2024-03-21 18:15
0.67.0 is out. Closing this issue. 

Please, check that it works there.

**Closed by tooltitude-support** 2024-03-21 18:15 UTC

**Comment by tooltitude-support** [comment] 2024-03-21 19:24
And again, thanks a lot for reporting bugs. Don't hesitate to report bug and ask for features in the future! We are really eager to fix bugs and implement new features (where it's reasonable).
